# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788a626665e622e20f553de3fe5134feaafd601b37c98a44658967f130c739476e5f44f4bd8326863cd949329d65cfc33b1d6899a2fe6777c4166feba5997868

test:
  secret_key_base: 7505c2a24475f9bb1fc7836bc38530bdb9d536fd3a1f8815b1dec66956aec8b4bef40bddea9cea4644185a0806541afb68e56b920d9dd0bcb4ba91ee9e2a555b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
